lunch/lunch/loans/urls.py
# loans/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.loan_list, name='loan_list'),
    url(r'^new/$', views.loan_create, name='loan_create'),
    url(r'^(?P<pk>\d+)/$', views.loan_detail, name='loan_detail'),
    url(r'^(?P<pk>\d+)/update/$', views.loan_update, name='loan_update'),
    url(r'^(?P<pk>\d+)/delete/$', views.loan_delete, name='loan_delete'),
    url(r'^utk/$', views.utk_search, name='utk_search'),
    url(r'^export/$', views.export_xlsx, name='export_xlsx'),
    #url(r'^utkvalue$', views.utk_value),
]

lunch/lunch/base/models.py
from django.db import models

# Create your models here.

lunch/lunch/loans/models.py
# loans/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import (
    MaxValueValidator, MinValueValidator, RegexValidator
)
from django.contrib.auth.models import User

class Log(models.Model):
    
    name = models.CharField(
        max_length=30,
        verbose_name=_('name'),
    )
    function = models.CharField(
        max_length=100,
        blank=True, null=True,
        verbose_name=_('function'),
    )
    info = models.CharField(
        max_length=100,
        blank=True, null=True,
        verbose_name=_('info'),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    class Meta:
        verbose_name = _('Log')
        verbose_name_plural = _('Logs')

    def __str__(self):
        return self.name

class Pegadri(models.Model):

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True,
        related_name='owned_laon_pegadri',
        verbose_name=_('owner'),
    )
    name = models.CharField(
        max_length=50,
        verbose_name=_('name'),
    )
    email = models.EmailField(
        blank=False, null=False,
        verbose_name=_('email'),
    )

    class Meta:
        verbose_name = _('Pegadri')
        verbose_name_plural = _('Pegadris')

    def __str__(self):
        return self.name+','+str(self.email)

    def get_absolute_url(self):
        return reverse('pegadri_detail', kwargs={'pk': self.pk})

    def can_user_delete(self, user):
        if not self.owner or self.owner == user:
            return True
        if user.has_perm('events.delete_pegadri'):
            return True
        return False

class Cocodri(models.Model):

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True,
        related_name='owned_loan_cocodri',
        verbose_name=_('owner'),
    )
    name = models.CharField(
        max_length=50,
        verbose_name=_('name'),
    )
    email = models.EmailField(
        blank=False, null=False,
        verbose_name=_('email'),
    )

    class Meta:
        verbose_name = _('Cocodri')
        verbose_name_plural = _('Cocodris')

    def __str__(self):
        return self.name+','+str(self.email)

    def get_absolute_url(self):
        return reverse('cocodri_detail', kwargs={'pk': self.pk})

    def can_user_delete(self, user):
        if not self.owner or self.owner == user:
            return True
        if user.has_perm('events.delete_cocodri'):
            return True
        return False

class Functionteam(models.Model):

    name = models.CharField(
        max_length=30,
        verbose_name=_('name'),
    )

    class Meta:
        verbose_name = _('Functionteam')
        verbose_name_plural = _('Functionteams')

    def __str__(self):
        return self.name

class Station(models.Model):

    name = models.CharField(
        max_length=30,
        verbose_name=_('name'),
    )

    class Meta:
        verbose_name = _('Station')
        verbose_name_plural = _('Stations')

    def __str__(self):
        return self.name

class Loan(models.Model):

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True, related_name='owned_loans',
    )
    function_team = models.ForeignKey(
        Functionteam,
        verbose_name=_('Function Team')
    )
    cocodri = models.ForeignKey(
        Cocodri, blank=False, null=True,
        related_name='cocodri_item', 
        verbose_name=_('CoCo DRI'),
    )
    pegadri = models.ForeignKey(
        Pegadri, blank=False, null=True,
        related_name='pegadri_item', 
        verbose_name=_('Pega DRI'),
    )
    purpose = models.CharField(
        max_length=100, null=True,
        validators=[
            RegexValidator(
               regex=r"^[a-z A-Z 0-9 \[^\u4e00-\u9fa5\] /,.?~!@#$%^&*()_+]*$",
               message='Chinese characters are restricted. Must be Alphanumeric \
                        (只接受英文、數字、半形符號)',
               code='invalid',
            ),
        ]
    )
    disassemble = models.BooleanField(
        #default=False,
        blank=False,
        verbose_name=_('Disassemble（會拆機台）'),
    )
    pega_dri_mail_group = models.CharField(
        max_length=300,
        null=True,
        verbose_name=_('Pega DRI Mail Group'),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = _('Loan')
        verbose_name_plural = _('Loans')

    def __str__(self):
        return self.purpose

    def get_absolute_url(self):
        return reverse('loan_detail', kwargs={'pk': self.pk})

    def can_user_delete(self, user):
        #if not self.owner or self.owner == user:
        #    return True
        if user.has_perm('loans.delete_store'):
            return True
        return False

class Device(models.Model):

    request = models.ForeignKey(
        'Loan',
        related_name='menu_items', 
        verbose_name=_('loan'),
    )
    station = models.ForeignKey(
        'Station',
        related_name='grpnm_items', 
        verbose_name=_('Station'),
    )
    config = models.CharField(
        max_length=10,
        blank=True, null=True,
    )
    unit_no = models.CharField(
        max_length=20,
        blank=True, null=True,
    )
    isn = models.CharField(
        max_length=20,
        blank=False, null=True,
        verbose_name=_('ISN'),
    )
    failure_symptoms = models.CharField(
        max_length=300,
        blank=False, null=True,
    )
    utk = models.CharField(
        max_length=300,
        blank=True, null=True,
    )
    grpnm = models.CharField(
        max_length=30,
        blank=True, null=True,
        verbose_name=_('GRPNM'),
    )
    # Below is for admin
    status = models.IntegerField(
        default=0,
    )
    is_approved = models.BooleanField(
        default=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    sfis_status = models.BooleanField(
        default=False,
    )
    sfis_info = models.CharField(
        max_length=40,
        blank=True, null=True,
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = _('Device')
        verbose_name_plural = _('Devices')

    def __str__(self):
        return self.isn

lunch/lunch/base/views.py
from django.shortcuts import render

# Create your views here.

lunch/lunch/loans/views.py
# loans/views.py
import logging
from datetime import datetime
from django.shortcuts import redirect, render
from .models import Loan, Device, Pegadri, Cocodri, Log
from django.http import Http404
#from django.forms.models import modelform_factory
from .forms import LoanForm, DeviceFormSet, AddpegadriForm, AddcocodriForm
from django.http import HttpResponseForbidden
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from django.forms.models import inlineformset_factory
from utility.pega_smtp import SMTP
from utility import HTML
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.http import JsonResponse
from .belta import Sfis

logger = logging.getLogger(__name__)

@login_required
def loan_list(request):
    loans = Loan.objects.all()
    Log.objects.create(name=request.user, function='loan list', info=None)
    return render(request, 'loans/loan_list.html', {'loans': loans})

@login_required
def loan_detail(request, pk):
    try:
        loan = Loan.objects.get(pk=pk)
    except Store.DoesNotExist:
        raise Http404
    Log.objects.create(name=request.user, function='loan detail', info=loan)
    return render(request, 'loans/loan_detail.html', {'loan': loan})

@login_required
def utk_search(request):
    if request.method == 'GET':
       #return render_to_response('loans/utk_search.html', locals())
       return render(request, 'loans/utk_search.html')

def utk_value(request):
    if request.method == 'POST':
        isn = request.POST.get('nickname','')
        #print('isn',isn)
        sfis = Sfis()
        s_utk = sfis.utk(isn)
        if s_utk[0] == 1:
            utk = {"UTK No Data":s_utk[1]}
        else:
            utk = s_utk[1]
        s_modd = sfis.modd(isn)
        if s_modd[0] == 1:
            modd = {"MODD No Data":s_modd[1]}
        else:
            modd = s_modd[1]
        print(type(utk), utk, type(modd), modd)
        Log.objects.create(name=request.user, function='utk search', info=str(isn)+str(utk)+str(modd))
        return JsonResponse(dict(utk, **modd))

@login_required
def loan_create(request):
    if request.method == 'POST':
        formp = AddpegadriForm()
        formc = AddcocodriForm()
        form = LoanForm(request.POST, submit_title='建立', user=request.user)
        if form.is_valid():
            loan = form.save(commit=False)
            if request.user.is_authenticated():
                loan.owner = request.user
            device_formset = DeviceFormSet(request.POST, instance=loan)
            if device_formset.is_valid():
                # send mail
                attach_mail = request.POST.getlist('pega_dri_mail_group')
                attach_mail = [Pegadri.objects.get(id=n).email for n in attach_mail]
                creater = User.objects.get(username=request.user).email
                #send_mail(request=loan, attach_mail=attach_mail, creater=creater)
                loan.save()
                device_formset.save()
                device_items = Device.objects.filter(request=loan)
                device_list = list()
                for i in range(0, len(device_items)):
                    # update sfis
                    try:
                        sfis = Sfis()
                    except Exception as e:
                        sfis = Sfis()

                    s_info = sfis.isninfo(device_items[i].isn)
                    s_utk = sfis.utk(device_items[i].isn)
                    s_error = sfis.error(device_items[i].isn, device_items[i].station)
                    s_modd = sfis.modd(device_items[i].isn)
                    if s_info[0] == 0:
                        info = s_info[1]
                        config = info['SN1'].split('/')[3]
                        unit_no = info['SN1'].split('/')[4]
                        Device.objects.filter(isn=device_items[i].isn).update(
                            config=config, unit_no=unit_no, sfis_status=True
                        )
                    else:
                        info = s_info[1]
                        config = 'no data'
                        unit_no = 'no data'
                        Device.objects.filter(isn=device_items[i].isn).update(
                            sfis_info=str(info)+','+str(datetime.strftime(datetime.now(),'%Y-%m-%d-%H:%M'))
                        )
                    if s_utk[0] == 0:
                        utk = s_utk[1]
                        Device.objects.filter(isn=device_items[i].isn).update(
                            utk=utk['UTK C_TIME']
                        )
                    if s_error[0] == 0:
                        serror = s_error[1]
                        failure_symptoms = serror['PDCS_LIST_OF_FAILTING_TEST']
                        Device.objects.filter(isn=device_items[i].isn).update(
                            failure_symptoms=failure_symptoms 
                        )
                    else:
                        serror = s_error[1]
                        failure_symptoms = str(serror)
                        Device.objects.filter(isn=device_items[i].isn).update(
                            failure_symptoms=str(serror)
                        )
                    if s_modd[0] == 0:
                       smodd = s_modd[1]
                       grpnm = str(smodd['MODD GRPNM'])+', '+str(smodd['MODD STATUS'])
                       Device.objects.filter(isn=device_items[i].isn).update(
                            grpnm=str(grpnm)
                        )
                    else:
                       smodd = s_modd[1]
                       grpnm = str(smodd)
                       Device.objects.filter(isn=device_items[i].isn).update(
                            grpnm=str(grpnm)
                        )
                    device_list.append(
                        [str(device_items[i].isn), str(device_items[i].station),
                         str(grpnm), str(config), str(unit_no),
                         str(failure_symptoms)]
                    )
                send_mail(request=loan, device=device_list, attach_mail=attach_mail, creater=creater)
                return redirect(loan.get_absolute_url())
        # TODO(yichieh): if form is fail, should also return device_formset value by user input.
        return render(request, 'loans/loan_create.html', {
            'form': form, 'formp': formp, 'formc': formc,
        })
    else:
        formp = AddpegadriForm()
        formc = AddcocodriForm()
        form = LoanForm(submit_title=None, user=request.user)
        form.helper.form_tag = False
        device_formset = DeviceFormSet()
    return render(request, 'loans/loan_create.html', {
        'form': form, 'formp': formp, 'formc': formc,
        'device_formset': device_formset,
    })

@login_required
@permission_required('loans.delete_store', login_url='/accounts/login/')
def loan_update(request, pk):
    try:
        loan = Loan.objects.get(pk=pk)
    except Loan.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = LoanForm(request.POST, instance=loan, submit_title='更新', user=request.user)
        # 用 post data 建立 formset，並在其（與 loan form）合法時儲存。
        device_formset = DeviceFormSet(request.POST, instance=loan)
        if form.is_valid() and device_formset.is_valid():
            loan = form.save()
            device_formset.save()
            return redirect(loan.get_absolute_url())
    else:
        # 移除 submit button 與 form tag。
        form = LoanForm(instance=loan, submit_title=None, user=request.user)
        form.helper.form_tag = False
        device_formset = DeviceFormSet(instance=loan)

    return render(request, 'loans/loan_update.html', {
        'form': form, 'loan': loan, 'device_formset': device_formset,
    })

@login_required
@require_http_methods(['POST', 'DELETE'])
def loan_delete(request, pk):
    try:
        loan = Loan.objects.get(pk=pk)
    except Loan.DoesNotExist:
        raise Http404
    '''
    if (not loan.owner or loan.owner == request.user
            or request.user.has_perm('loan_delete')):
        loan.delete()
        return redirect('loan_list')
    '''
    if loan.can_user_delete(request.user):
        loan.delete()
        if request.is_ajax():
            return HttpResponse()
        return redirect('loan_list')
    return HttpResponseForbidden()

def adddri_pega(request):
    if request.method == 'POST':
        formp = AddpegadriForm(request.POST)
        if formp.is_valid():
            post = formp.save(commit=False)
            post.author = request.user
            post.owner = request.user
            post.save()
            # get the user id from db
            select_id = Pegadri.objects.filter(name=post.name)
            select_id = select_id[len(select_id)-1].id
            return HttpResponse(select_id)
    return HttpResponse("False")

def adddri_coco(request):
    if request.method == 'POST':
        formc = AddcocodriForm(request.POST)
        if formc.is_valid():
            post = formc.save(commit=False)
            post.author = request.user
            post.owner = request.user
            post.save()
            # get the user id from db
            select_id = Cocodri.objects.filter(name=post.name)
            select_id = select_id[len(select_id)-1].id
            return HttpResponse(select_id)
    return HttpResponse("False")

def send_mail(request, device, attach_mail, creater):
    # pega dri and coco dir should be unie.
    pega_dri_email = request.pegadri.email
    coco_dri_email = request.cocodri.email
    mail_group = [
        pega_dri_email, coco_dri_email, creater,

lunch/lunch/loans/templates/loans/base.html
{% extends 'base.html' %}

{% block body %}
{{ block.super }}
<div class="container">{% block content %}{% endblock content %}</div>
{% endblock body %}

lunch/lunch/loans/templates/loans/loan_create.html
{# loans/templates/loans/loan_create.html #}

{% extends 'loans/base.html' %}
{% load staticfiles crispy_forms_tags %}

{% block title %}Units Checkin | {{ block.super }}{% endblock title %}

{% block content %}
<form method="post">
  {% crispy form %}

  <!-- 手動一個一個產生 formset 中的 forms，並在它們外面包一層 div -->
  {{ device_formset.management_form }}
  {% for form in device_formset %}
    <div class="menu-item form-group">
      {% crispy form device_formset.helper %}
    </div>
  {% endfor %}

  <!-- 增加這行 -->
  <section class="progress-demo">
  <a href="#" class="menu-item-add btn btn-default">新增項目</a>
  {# <button type="submit" class="btn btn-primary">更新</button> #}
  <button type="submit" class="btn btn-primary ladda-button" data-style="expand-right">提交</button>
  </section>

  <!-- Modal Pega DRI update-->
  <div class="modal fade" id="pegaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="exampleModalLabel">New message</h4>
        </div>
        <div class="modal-body">
          <form role="form">
            {{ formp|crispy }}
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button id="pegasave" type="button" class="btn btn-primary">Save</button>
          <!-- <button type="submit" class="btn btn-primary">Test</button> -->
        </div>
      </div>
    </div>
  </div>

  <!-- Modal CoCo DRI update-->
  <div class="modal fade" id="cocoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="exampleModalLabel">New message</h4>
        </div>
        <div class="modal-body">
          <form role="form">
            {{ formc|crispy }}
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button id="cocosave" type="button" class="btn btn-success">Save</button>
          <!-- <button type="submit" class="btn btn-primary">Test</button> -->
        </div>
      </div>
    </div>
  </div>

  <!-- Button trigger modal -->
  <!-- Modal status -->
  <div class="modal fade" id="statusModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">通知</h4>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>  

</form>
{% endblock content %}

<!-- 加上這個 block -->
{% block js %}
{{ block.super }}
<script>$('#id_pega_dri_mail_group').multiSelect()</script>
<script src="{% static 'loans/js/loan_update.js' %}"></script>
<script src="{% static 'loans/js/loan_addp.js' %}"></script>
<script src="{% static 'loans/js/loan_addc.js' %}"></script>
{% endblock js %}

lunch/lunch/loans/templates/loans/loan_detail.html
{# loans/templates/loan_detail.html #}

{% extends 'loans/base.html' %}
{% load crispy_forms_tags loans_tags %}

{% block title %}{{ loan.purpose }} | {{ block.super }}{% endblock title %}

{% block content%}
<form method="post" action="{% url 'loan_delete' loan.pk %}">
  {% csrf_token %}
  <a href="{% url 'loan_update' pk=loan.pk %}" class="btn btn-default">更新清單</a>
  {% if loan|deletable:user %}
  <button type="submit" class="btn btn-danger">刪除</button>
  {% endif %}
</form>

<h1>#{{ loan.id }}_{{ loan.purpose }}</h1>
{# <p>{{ loan.disassemble }}</p> #}
 <table class="table table-striped table table-hover" style="font-size:12px;">
  <thead>
    <tr><th>ISN</th><th>Config</th><th>Unit No.</th>
      <th>Station</th><th>Failure Symptoms</th>
      <th>UTK</th><th>GRPNM</th><th>Create Date</th>
      <th>S_Status</th><th>S_Info</th>
      <th>Approved</th><th>Admin</th>
    </tr>
  </thead>
  <tbody>
    {% for item in loan.menu_items.all %}
    <tr>
      <td>{{ item.isn }}</td><td>{{ item.config }}</td>
      <td>{{ item.unit_no }}</td><td>{{ item.station}}</td>
      <td>{{ item.failure_symptoms }}</td><td>{{ item.utk}}</td>
      <td>{{ item.grpnm }}</td><td>{{ item.created_at }}</td>
      <td>{{ item.sfis_status }}</td><td>{{ item.sfis_info }}</td>
      <td>{{ item.is_approved }}</td><td></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

lunch/lunch/loans/templates/loans/loan_list.html
{# loans/templates/loan_list.html #}
{% extends 'loans/base.html' %}
{% load staticfiles crispy_forms_tags loans_tags %}

{% block title %}列表 | {{ block.super }}{% endblock title %}

{% block content %}
<a href="{% url 'loan_create' %}" class="btn btn-default">Units Checkin FA Request List</a>

{% for loan in loans %}
<div class="loan">
  {% if loan|deletable:user %}
  <button data-href="{% url 'loan_delete' loan.pk %}"
    class="btn btn-danger pull-right btn-delete">刪除
  </button>
  {% endif %}
  <h2><a href="{{ loan.get_absolute_url }}">#{{ loan.id }} {{ loan.function_team }}({{ loan.owner }})</a></h2>
  <p>Coco:{{ loan.cocodri }}, Pega:{{ loan.pegadri }}, Purpose:{{ loan.purpose }}, Disassemble:{{loan.disassemble}}, Time:{{ loan.created_at}}</p>
   <table class="table table-striped table table-hover" style="font-size:12px;">
    <thead>
      <tr><th>Function</th><th>ISN</th>
      <th>Config</th><th>Unit_no</th>
      <th>Station</th><th>GRPNM</th><th>Failure Symptoms</th>
      <th>UTK</th><th>Create Date</th>
      <th>Approved</th><th>Admin</th>
      </tr>
    </thead>
    <tbody>
    {% for item in loan.menu_items.all %}
    <tr>
      <td>{{ loan.function_team}}</td>
      <td>{{ item.isn }}</td><td>{{ item.config }}</td>
      <td>{{ item.unit_no }}</td><td>{{ item.station}}</td>
      <td>{{ item.grpnm }}</td>
      <td>{{ item.failure_symptoms }}</td><td>{{ item.utk}}</td>
      <td>{{ item.created_at }}</td>
      <td>{{ item.is_approved }}</td><td></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endfor %}

{% endblock content %}

{% block js %}
<script src="{% static 'loans/js/loan_list.js' %}"></script>
{% endblock js %}

lunch/lunch/loans/templates/loans/loan_update.html
{% extends 'loans/base.html' %}
{% load staticfiles crispy_forms_tags %}


{% block title %}更新 {{ loan.purpose }} | {{ block.super }}{% endblock title %}


{% block content %}

<form method="post">

  {% crispy form %}

  {{ device_formset.management_form }}
  {% for form in device_formset %}
    <div class="menu-item form-group">
      {% crispy form device_formset.helper %}
    </div>
  {% endfor %}

  <a href="#" class="menu-item-add btn btn-default">新增項目</a>
  <button type="submit" class="btn btn-primary">更新</button>

</form>

{% endblock content %}


{% block js %}
{{ block.super }}
<script> $('#id_pega_dri_mail_group').multiSelect() </script>
<script src="{% static 'loans/js/loan_update.js' %}"></script>
{% endblock js %}

lunch/lunch/loans/templates/loans/utk_search.html
{# loans/templates/loans/utk_search.html #}

{% extends 'loans/base.html' %}
{% load staticfiles %}

{% block title %}UTK Search | {{ block.super }}{% endblock title %}

{% block content %}
<html>
<body>
  <p><a href="http://yodawebs/index.jsp">完整訊息請上SFIS查詢</a></p>
  <p>可查詢最新一筆SFIS UTK,MODD訊息, 等候時間約1~30s, 推薦使用Chrome瀏覽器.</p>
  <p>ISN: <input type="text" name="nickname" /></p>
  <input class="name_submit" type="submit" value="Submit" />
  <div class="name_value"></div>
</body>

<script src="{% static 'base/js/jquery-2.2.1.min.js' %}"></script>
<script src="{% static 'loans/js/loan_search.js' %}"></script>
{#<script type="text/javascript"></script>#}
</html>

{% endblock content %}

<!-- 加上這個 block -->
{% block js %}
{{ block.super }}

{% endblock js %}